import pandas as pd
import os
import json
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class GraphVisualizer:

    def __init__(self, output_dir="./ragtest/output"):
        self.output_dir = Path(output_dir)

    def extract_graph_data(self):
        """Extract graph data from parquet files generated by GraphRAG indexing."""
        try:
            if not self.output_dir.exists():
                logger.warning(f"Output path not found: {self.output_dir}")
                return {"nodes": [], "edges": [], "stats": {}}

            entities_file = None
            relationships_file = None

            # Search for parquet files recursively
            for root, dirs, files in os.walk(self.output_dir):
                for file in files:
                    name = file.lower()
                    full_path = os.path.join(root, file)

                    if "entities" in name and name.endswith(".parquet"):
                        entities_file = full_path
                    elif "relationships" in name and name.endswith(".parquet"):
                        relationships_file = full_path
                    # Also check for create_final_nodes / create_final_relationships
                    elif "nodes" in name and name.endswith(".parquet") and entities_file is None:
                        entities_file = full_path
                    elif "edges" in name and name.endswith(".parquet") and relationships_file is None:
                        relationships_file = full_path

            if entities_file is None:
                logger.warning("Arquivo de entidades (.parquet) não encontrado")
                return {"nodes": [], "edges": [], "stats": {}}

            logger.info(f"Entities file: {entities_file}")
            if relationships_file:
                logger.info(f"Relationships file: {relationships_file}")

            # Read entities
            df_entities = pd.read_parquet(entities_file)
            logger.info(f"Entity columns: {list(df_entities.columns)}")

            nodes = []
            for _, row in df_entities.iterrows():
                # Handle different column naming conventions
                node_id = str(
                    row.get("id", row.get("title", row.get("name", row.get("entity", ""))))
                )
                label = str(
                    row.get("title", row.get("name", row.get("entity", node_id)))
                )
                entity_type = str(row.get("type", row.get("entity_type", "unknown")))
                description = str(row.get("description", ""))[:200]

                nodes.append({
                    "id": node_id,
                    "label": label,
                    "type": entity_type,
                    "description": description,
                    "size": 20
                })

            # Read relationships
            edges = []
            if relationships_file:
                df_relationships = pd.read_parquet(relationships_file)
                logger.info(f"Relationship columns: {list(df_relationships.columns)}")

                for _, row in df_relationships.iterrows():
                    source = str(row.get("source", row.get("head", "")))
                    target = str(row.get("target", row.get("tail", "")))
                    relationship = str(row.get("description", row.get("label", row.get("type", ""))))

                    if source and target:
                        edges.append({
                            "source": source,
                            "target": target,
                            "relationship": relationship[:100],
                            "weight": float(row.get("weight", row.get("rank", 1)))
                        })

            # Calculate statistics
            community_col = None
            for col in ["community", "community_id", "cluster"]:
                if col in df_entities.columns:
                    community_col = col
                    break

            stats = {
                "total_entities": len(nodes),
                "total_relationships": len(edges),
                "communities": int(df_entities[community_col].nunique()) if community_col else 0,
                "avg_degree": round((2 * len(edges)) / max(len(nodes), 1), 2)
            }

            logger.info(f"{len(nodes)} entidades carregadas")
            logger.info(f"{len(edges)} relacionamentos carregados")

            return {"nodes": nodes, "edges": edges, "stats": stats}

        except Exception as e:
            logger.exception(f"Error extracting graph data: {e}")
            return {"nodes": [], "edges": [], "stats": {}}

    def get_graph_summary(self):
        """Get a text summary of the graph."""
        data = self.extract_graph_data()

        if not data["nodes"]:
            return "Nenhum grafo encontrado."

        s = data["stats"]
        return (
            f"**Entidades:** {s['total_entities']} | "
            f"**Relacionamentos:** {s['total_relationships']} | "
            f"**Comunidades:** {s['communities']} | "
            f"**Grau Médio:** {s['avg_degree']}"
        )

    def get_top_entities(self, n=10):
        """Get top entities by degree (number of connections)."""
        data = self.extract_graph_data()

        degree = {}
        for edge in data["edges"]:
            degree[edge["source"]] = degree.get(edge["source"], 0) + 1
            degree[edge["target"]] = degree.get(edge["target"], 0) + 1

        return sorted(degree.items(), key=lambda x: x[1], reverse=True)[:n]

    def get_graph_json(self):
        """Return graph data as JSON string."""
        return json.dumps(self.extract_graph_data(), ensure_ascii=False)
